package cloud.azaeem.recipe.ui.theme

import androidx.compose.ui.graphics.Color

val Seed = Color(0xFFF44336) 

val LightPrimary = Color(0xFFBF360C)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFFFCCBC)
val LightOnPrimaryContainer = Color(0xFF3E2723)
val LightSecondary = Color(0xFF5D4037)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFD7CCC8)
val LightOnSecondaryContainer = Color(0xFF1B1B1B)
val LightTertiary = Color(0xFFF57C00)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFFFE0B2)
val LightOnTertiaryContainer = Color(0xFF212121)
val LightError = Color(0xFFB00020)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFF9DEDC)
val LightOnErrorContainer = Color(0xFF410002)
val LightBackground = Color(0xFFFFF8F1)
val LightOnBackground = Color(0xFF1B1B1B)
val LightSurface = Color(0xFFFFF8F1)
val LightOnSurface = Color(0xFF1B1B1B)
val LightSurfaceVariant = Color(0xFFF4EBE6)
val LightOnSurfaceVariant = Color(0xFF4E443F)
val LightOutline = Color(0xFF85736C)

val DarkPrimary = Color(0xFFFFAB91)
val DarkOnPrimary = Color(0xFF5D4037)
val DarkPrimaryContainer = Color(0xFF8E24AA)
val DarkOnPrimaryContainer = Color(0xFFFFCCBC)
val DarkSecondary = Color(0xFFD7CCC8)
val DarkOnSecondary = Color(0xFF3E2723)
val DarkSecondaryContainer = Color(0xFF4E342E)
val DarkOnSecondaryContainer = Color(0xFFD7CCC8)
val DarkTertiary = Color(0xFFFFB74D)
val DarkOnTertiary = Color(0xFFE65100)
val DarkTertiaryContainer = Color(0xFFFB8C00)
val DarkOnTertiaryContainer = Color(0xFFFFE0B2)
val DarkError = Color(0xFFF2B8B5)
val DarkOnError = Color(0xFF601410)
val DarkErrorContainer = Color(0xFF8C1D18)
val DarkOnErrorContainer = Color(0xFFF9DEDC)
val DarkBackground = Color(0xFF1B1B1B)
val DarkOnBackground = Color(0xFFEDE0D4)
val DarkSurface = Color(0xFF1B1B1B)
val DarkOnSurface = Color(0xFFEDE0D4)
val DarkSurfaceVariant = Color(0xFF4E443F)
val DarkOnSurfaceVariant = Color(0xFFD5C4BC)
val DarkOutline = Color(0xFFA08D85)
